services:
  # --- SQL SERVER ---
  tuuuur_sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tuuuur_sqlserver
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - tuuuur-db:/var/opt/mssql
    healthcheck:
      test: >
        /bin/sh -c "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -C -Q 'SELECT 1' || exit 1"
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 40s
    networks:
      - tuuur-network

  # --- REDIS ---
  tuuuur_redis:
    image: redis:latest
    container_name: tuuuur_redis
    restart: always
    command: redis-server --requirepass "YourStrong!RedisPass"
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "YourStrong!RedisPass", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tuuur-network

  # --- MIGRATIONS ---
  tuuuur_migrate:
    platform: linux/amd64
    build:
      context: .
      dockerfile: src/Tuuuur.Database/Dockerfile
    container_name: tuuuur_migrate
    depends_on:
      tuuuur_sqlserver:
        condition: service_healthy
    environment:
      - DB_SERVER=tuuuur_sqlserver
      - DB_NAME=Tuuuur-dev
      - DB_USER=sa
      - DB_PASSWORD=YourStrong!Passw0rd
    restart: "no"
    networks:
      - tuuur-network

  # --- API ---
  api:
    build:
      context: .
      dockerfile: src/Tuuuur.API/Dockerfile
    container_name: tuuuur_api
    restart: always
    depends_on:
      tuuuur_sqlserver:
        condition: service_healthy
      tuuuur_redis:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Tuuuur=Server=tuuuur_sqlserver,1433;Initial Catalog=Tuuuur-dev;Persist Security Info=False;User ID=sa;Password=YourStrong!Passw0rd;MultipleActiveResultSets=False;Encrypt=False;TrustServerCertificate=True;Connection Timeout=30
      - ConnectionStrings__Redis=tuuuur_redis:6379,password=YourStrong!RedisPass
      - JwtSettings__Key=${JWT_KEY}
      - Authentification__Google__ClientId=${GOOGLE_CLIENT_ID}
      - SmtpEmailConfiguration__FromAddress=${SMTP_FROM_ADDRESS}
      - SmtpEmailConfiguration__FromName=${SMTP_FROM_NAME}
      - SmtpEmailConfiguration__SmtpAddress=${SMTP_HOST}
      - SmtpEmailConfiguration__SmtpPort=${SMTP_PORT}
      - SmtpEmailConfiguration__SmtpLogin=${SMTP_USER}
      - SmtpEmailConfiguration__SmtpPassword=${SMTP_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - ./data-protection:/root/.aspnet/DataProtection-Keys
    networks:
      - tuuur-network

networks:
  tuuur-network:
    driver: bridge

volumes:
  tuuuur-db: