name: build

on:
  workflow_call:
    inputs:
      configuration:
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup .NET
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
        with:
          dotnet-version: 8.0.x

      - name: Restore packages
        run: dotnet restore --locked-mode --force-evaluate

      - name: Build solution
        env:
          BUILD_CONFIG: ${{ inputs.configuration }}
        run: dotnet build --configuration $env:BUILD_CONFIG --no-restore