name: build

on:
  workflow_call:
    inputs:
      configuration:
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore packages
        run: dotnet restore --locked-mode --force-evaluate

      - name: Build solution
        run: dotnet build --configuration ${{ inputs.configuration }} --no-restore
