name: CD - Master (Production)

on:
  push:
    branches:
      - master

jobs:
  docker-push:
    uses: ./.github/workflows/cd-docker-push.yml
    with:
      environment_name: "Production"
      docker_tags: "${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/tuuuur/api:latest,${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/tuuuur/api:prod-${{ github.sha }}"
    secrets:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
