name: CD - Production

on:
  push:
    branches:
      - master

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      configuration: Release

  build-and-deploy:
    needs: test
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      docker_tags: |
        ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REPOSITORY }}/tuuuur-api:latest
        ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REPOSITORY }}/tuuuur-api:${{ github.sha }}
    secrets: inherit
