name: CD - Release (Preprod)

on:
  push:
    branches:
      - release

jobs:
  docker-push:
    uses: ./.github/workflows/cd-docker-push.yml
    with:
      environment_name: "Preprod"
      docker_tags: "${{ vars.DOCKER_USERNAME }}/tuuuur-api:preprod,${{ vars.DOCKER_USERNAME }}/tuuuur-api:preprod-${{ github.sha }}"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
