name: CD Production

on:
  push:
    branches:
      - master

jobs:
  deploy_prod:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/templates/deploy-template.yml
        with:
          deploy-environment: "production"
