name: CI - Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      configuration: Debug

  test:
    needs: build
    uses: ./.github/workflows/test.yml
    with:
      configuration: Debug
