name: CI - Pull Request

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      configuration: Debug

  test:
    needs: build
    uses: ./.github/workflows/test.yml
    with:
      configuration: Debug

  # sonar:
  #   needs: test
  #   uses: ./.github/workflows/sonar.yml
  #   with:
  #     projectName: TuuuurAPI
  #     branchName: ${{ github.head_ref }}
  #   secrets:
  #     projectKey: ${{ secrets.PROJECT_KEY }}
  #     sonarToken: ${{ secrets.SONAR_TOKEN }}
  #     sonarHost: ${{ secrets.SONAR_HOST_URL }}
  #     sonarOrganization: ${{ secrets.SONAR_ORGANIZATION_URL }}
