name: CI Pipeline

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  ci:
    uses: ./.github/workflows/ci-template.yml
    with:
      project-key: "TuuuurAPI"
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      sonar-host: ${{ secrets.SONAR_HOST_URL }}
