name: CI Pipeline

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  ci:
    name: Build + Tests + SonarQube
    runs-on: windows-latest
    steps:
      - uses: ./.github/workflows/templates/ci-template.yml
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          sonar-host: ${{ secrets.SONAR_HOST_URL }}
          project-key: "TuuuurAPI"
