name: CI - Build, Tests & Sonar

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    uses: ./.github/workflows/templates/build.yml
    with:
      configuration: Release

  test:
    needs: build
    uses: ./.github/workflows/templates/test.yml
    with:
      configuration: Release

  sonar:
    needs: test
    uses: ./.github/workflows/templates/sonar.yml
    with:
      projectKey: TuuuurAPI
      sonarHost: ${{ secrets.SONAR_HOST_URL }}
      sonarToken: ${{ secrets.SONAR_TOKEN }}
