name: Deploy Template
on:
  workflow_call:
    inputs:
      deploy-environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: |
          echo "Déploiement sur l'environnement ${{ inputs.deploy-environment }}"
          # Remplacer par tes scripts réels
