name: sonar

on:
  workflow_call:
    inputs:
      projectKey:
        required: true
        type: string
    secrets:
      sonarToken:
        required: true
      sonarHost:
        required: true

jobs:
  sonar:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Begin SonarQube analysis
        run: |
          dotnet sonarscanner begin `
            /k:"${{ inputs.projectKey }}" `
            /d:sonar.host.url="${{ secrets.sonarHost }}" `
            /d:sonar.token="${{ secrets.sonarToken }}" `
            /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/*.cobertura.xml"

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build for Sonar
        run: dotnet build --configuration Release --no-restore

      - name: End SonarQube analysis
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.sonarToken }}"

