name: test

on:
  workflow_call:
    inputs:
      configuration:
        required: true
        type: string

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Run unit tests with coverage
        run: |
          Get-ChildItem -Path tests -Recurse -Filter *.Tests.csproj | ForEach-Object {
            dotnet test $_.FullName `
              --configuration ${{ inputs.configuration }} `
              --no-build `
              --verbosity normal `
              /p:CollectCoverage=true `
              /p:CoverletOutputFormat=cobertura `
              /p:CoverletOutput=TestResults/
          }

      - name: Publish coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: TestResults/**/*.cobertura.xml
